//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZakladFryzjerski.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myappEntities : DbContext
    {
        public myappEntities()
            : base("name=myappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fryzjer> Fryzjers { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Usługa> Usługa { get; set; }
        public virtual DbSet<Wizyta> Wizytas { get; set; }
    }
}
